### ISSUE TITLE
Create a kalisio user with sudo rights on machines

### ISSUE THREAD

**Issue by robinbourianes-frizko** [kalisio/kaabah#159]
This way every machine can be accessed using the same user, no more ubuntu on some, root on others ...
Scripts could also assume that calling sudo some_command would work.

**Comment by cnouguier** [comment]
The username should be a terraform variable.
The user should also belong to docker group

**Comment by robinbourianes-frizko** [comment]
We use cloudinit to setup instance with an admin user now.
