### ISSUE TITLE
 Unable to connect to an instance on Scaleway after reboot or waking up from standby mode

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kaabah#160]
It looks like the` authorized_keys` file is erased at every boot. It requires to use the AUTHORIZED_KEY tag to set it up permanently

**Comment by robinbourianes-frizko** [comment]
This looks like a bug with scaleway's `authorized_keys` handling process ...
Fixed as we now create our own admin user and copy the public key manually.

**Comment by cheoa** [comment]
Not done. Same problem. Unable to connect to an instance on Scaleway after waking up from standby mode.
