### ISSUE TITLE
Provision wait-for-it on the manager nodes

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kaabah#186]
[wait-for-it is](https://github.com/vishnubob/wait-for-it) useful for synchronizing the spin-up of interdependent services, such as linked docker containers.
Since we use debian, there is a package we can use : https://tracker.debian.org/pkg/wait-for-it

**Comment by robinbourianes-frizko** [comment]
Closed with 94948294818b2b64833b6dd712e543ef038b0762 even if commit message closes the wrong issue ;(
